apiVersion: v1
kind: Namespace
metadata:
  name: mdas
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: mdas
spec:
  containers:
  - image: nginx
    name: mynginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservicefornginx
  name: mynginx
  namespace: mdas
spec:
  ports:
  - nodePort: 30915
    port: 80
    targetPort: 80
  selector:
    app: mynginx
  sessionAffinity: None
  type: NodePort

