apiVersion: v1
kind: Namespace
metadata:
  name: votingapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvotingapp
spec:
  selector:
    matchLabels:
      app: myvotingapp
  replicas: 2
  template:
    metadata:
      namespace: votingapp
      labels:
        app: myvotingapp
    spec:
      containers:
        - name: myvotingapp
          image: john/votingapp
          env:
            - name: REDIS
              value: "myredis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: votingapp
  namespace: votingapp
spec:
  ports:
  - nodePort: 31647
    port: 80
    targetPort: 80
  selector:
    app: votingapp
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myredis
spec:
  selector:
    matchLabels:
      app: myredis
  replicas: 1
  template:
    metadata:
      namespace: votingapp
      labels:
        app: myredis
    spec:
      containers:
      - name: myredis
        image: redis
          
---
apiVersion: v1
kind: Service
metadata:
  name: myredis
  namespace: votingapp
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: myredis
  sessionAffinity: None
  type: NodePort